trigger: [master]

pr: [master]

jobs:
  - template: ci/job.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04
  - template: ci/job.yml
    parameters:
      name: MacOS
      vmImage: macos-10.13
  - template: ci/job.yml
    parameters:
      name: Windows
      vmImage: ubuntu-16.04
