trigger: [master]

pr: [master]

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    strategy: &strategy
      matrix:
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'

    steps:  &steps
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt pytest-cov
      displayName: dependencies

    - script: |
        pip install pytest pytest-azurepipelines
        pytest
      displayName: pytest

  - job: MacOS
    pool:
      vmImage: macos-10.13
    strategy: *strategy
    steps: *steps

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    strategy: *strategy
    steps: *steps
