parameters:
  name: Linux
  vmImage: ubuntu-16.04

jobs:
- job: ${{ parameters.name }}
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt -r requirements-dev.txt pytest-cov pytest-azurepipelines .
    displayName: dependencies

  - ${{ if eq(parameters.name, 'Windows') }}:
    - script: |
        where owlrl.py > delete-me
        set /p OWLRLPY=<delete-me
        del %OWLRLPY% delete-me
      displayName: clean up owlrl.py

  - ${{ if not(eq(parameters.name, 'Windows')) }}:
    - script: |
        rm $(which owlrl.py)
      displayName: clean up owlrl.py

  - script: |
      pytest --cov=pyshacl --cov-report=xml
    displayName: pytest
